name: build

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.20.0
        with:
          java-distribution: graalvm
          java-version: 21
          maven-version: 4.0.0-rc-6
          cache-enabled: true

      - name: Maven build
        run: mvn --batch-mode --update-snapshots verify
